import { useState, useEffect } from 'react'
import { useTranslation } from 'react-i18next'
import { Plus, Loader2, Info, RefreshCw } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Badge } from '@/components/ui/badge'
import { Tooltip, TooltipContent, TooltipTrigger } from '@/components/ui/tooltip'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog'

function generateSecret(): string {
  const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZabcdefghjkmnpqrstuvwxyz23456789'
  let result = 'vpp-'
  for (let i = 0; i < 12; i++) {
    result += chars.charAt(Math.floor(Math.random() * chars.length))
  }
  return result
}

interface RegisterSurveyDialogProps {
  onRegister: (data: {
    surveyId: number
    points: number
    secret: string
    maxClaims: number
    title: string
  }) => Promise<void>
  nextSurveyId: number
}

export function RegisterSurveyDialog({ onRegister, nextSurveyId }: RegisterSurveyDialogProps) {
  const { t } = useTranslation()
  const [open, setOpen] = useState(false)
  const [loading, setLoading] = useState(false)
  const [form, setForm] = useState({
    title: '',
    surveyId: '',
    points: '',
    secret: '',
  })

  useEffect(() => {
    if (open) {
      setForm({
        title: '',
        surveyId: String(nextSurveyId),
        points: '1',
        secret: generateSecret(),
      })
    }
  }, [open, nextSurveyId])

  const regenerateSecret = () => {
    setForm((f) => ({ ...f, secret: generateSecret() }))
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setLoading(true)
    try {
      await onRegister({
        surveyId: Number(form.surveyId),
        points: Number(form.points),
        secret: form.secret,
        maxClaims: 0,
        title: form.title,
      })
      setOpen(false)
    } finally {
      setLoading(false)
    }
  }

  const isValid =
    form.title.trim() &&
    form.surveyId &&
    form.points &&
    form.secret &&
    Number(form.surveyId) > 0 &&
    Number(form.points) > 0

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        <Button>
          <Plus className="mr-2 size-4" />
          {t('admin.surveys.register')}
        </Button>
      </DialogTrigger>
      <DialogContent>
        <form onSubmit={handleSubmit}>
          <DialogHeader>
            <DialogTitle>{t('admin.register.title')}</DialogTitle>
            <DialogDescription>{t('admin.surveys.register')}</DialogDescription>
          </DialogHeader>
          <div className="mt-4 space-y-4">
            <div className="space-y-2">
              <div className="flex items-center gap-1">
                <Label htmlFor="reg-title">{t('admin.register.surveyTitle')}</Label>
                <InfoTip text={t('admin.info.title')} />
              </div>
              <Input
                id="reg-title"
                type="text"
                placeholder={t('admin.register.surveyTitlePlaceholder')}
                value={form.title}
                onChange={(e) => setForm((f) => ({ ...f, title: e.target.value }))}
                required
              />
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label htmlFor="reg-points">{t('admin.register.points')}</Label>
                <Input
                  id="reg-points"
                  type="number"
                  min="1"
                  max="255"
                  value={form.points}
                  onChange={(e) => setForm((f) => ({ ...f, points: e.target.value }))}
                  required
                />
              </div>
              <div className="space-y-2">
                <div className="flex items-center gap-1">
                  <Label htmlFor="reg-surveyId">{t('admin.register.surveyId')}</Label>
                  <InfoTip text={t('admin.info.surveyId')} />
                </div>
                <div className="relative">
                  <Input
                    id="reg-surveyId"
                    type="number"
                    min="1"
                    value={form.surveyId}
                    onChange={(e) => setForm((f) => ({ ...f, surveyId: e.target.value }))}
                    required
                  />
                  <Badge
                    variant="secondary"
                    className="absolute right-2 top-1/2 -translate-y-1/2 text-[10px]"
                  >
                    {t('admin.register.autoGenerated')}
                  </Badge>
                </div>
              </div>
            </div>
            <div className="space-y-2">
              <div className="flex items-center gap-1">
                <Label htmlFor="reg-secret">{t('admin.register.secret')}</Label>
                <InfoTip text={t('admin.info.secret')} />
              </div>
              <div className="flex gap-2">
                <div className="relative flex-1">
                  <Input
                    id="reg-secret"
                    type="text"
                    value={form.secret}
                    onChange={(e) => setForm((f) => ({ ...f, secret: e.target.value }))}
                    className="font-mono pr-24"
                    required
                  />
                  <Badge
                    variant="secondary"
                    className="absolute right-2 top-1/2 -translate-y-1/2 text-[10px]"
                  >
                    {t('admin.register.autoGenerated')}
                  </Badge>
                </div>
                <Button
                  type="button"
                  variant="outline"
                  size="icon"
                  onClick={regenerateSecret}
                  aria-label={t('admin.register.regenerateSecret', 'Neues Secret generieren')}
                >
                  <RefreshCw className="size-4" aria-hidden="true" />
                </Button>
              </div>
            </div>
          </div>
          <DialogFooter className="mt-6">
            <Button type="button" variant="outline" onClick={() => setOpen(false)}>
              {t('common.cancel')}
            </Button>
            <Button type="submit" disabled={!isValid || loading}>
              {loading ? (
                <>
                  <Loader2 className="mr-2 size-4 animate-spin" />
                  {t('common.loading')}
                </>
              ) : (
                t('admin.register.button')
              )}
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  )
}

function InfoTip({ text }: { text: string }) {
  return (
    <Tooltip>
      <TooltipTrigger asChild>
        <button
          type="button"
          className="inline-flex size-5 items-center justify-center rounded-full text-muted-foreground hover:text-foreground"
          aria-label="Info"
        >
          <Info className="size-3.5" aria-hidden="true" />
        </button>
      </TooltipTrigger>
      <TooltipContent side="top" className="max-w-xs text-xs">
        {text}
      </TooltipContent>
    </Tooltip>
  )
}
