/**
 * @module atomic-write
 *
 * Helpers for the four JSON-file stores under `packages/backend/data/`:
 *   - events.json
 *   - admin-labels.json
 *   - used-nonces.json
 *   - survey-keys.json
 *
 * Two responsibilities:
 *
 * 1. **Atomic writes.** Write to a sibling `<path>.tmp`, then rename. POSIX
 *    rename is atomic, so a Plesk hard-restart between the two operations
 *    leaves the canonical file as either the previous valid version or the
 *    new valid version — never a half-truncated JSON that crashes boot.
 *
 * 2. **Strict file permissions.** Plesk shared-tenant hosting means another
 *    tenant on the same box could in principle read world-readable files in
 *    our `data/` directory. We therefore create the dir as `0o700` and every
 *    file as `0o600`, and we drop a `.htaccess` deny-from-all in the dir as
 *    a second layer for the case where Plesk publishes the path under a
 *    static-files vhost (audit M13 / F4.5).
 */
import { existsSync, mkdirSync, writeFileSync, renameSync, chmodSync, statSync } from 'node:fs'
import { dirname } from 'node:path'
import { logger } from './logger.js'

/** chmod 0700 — directory readable + writable + executable only by owner. */
const DIR_MODE = 0o700

/** chmod 0600 — file readable + writable only by owner. */
const FILE_MODE = 0o600

const HTACCESS_BODY = `# Generated by packages/backend/src/lib/atomic-write.ts on every boot.
# Defense-in-depth deny for the data/ directory on Plesk Apache. The
# directory should never be publicly served (Phusion Passenger only invokes
# our app.js entry point), but if a future Plesk reconfiguration exposes
# the path as static files, this rule makes Apache return 403 for any
# request to data/* instead of leaking *.json contents.
<IfModule mod_authz_core.c>
    Require all denied
</IfModule>
<IfModule !mod_authz_core.c>
    Order deny,allow
    Deny from all
</IfModule>
`

/**
 * Idempotently ensures `dir` exists with mode 0700 and contains an
 * `.htaccess` deny-all. Safe to call from every store on every save.
 *
 * Permission tightening is best-effort: on filesystems that don't honor
 * POSIX modes (Windows, some FUSE mounts), the chmod call may be a no-op
 * or throw — we log a warning and continue rather than refusing to write
 * the store, because losing data integrity to gain permission strictness
 * would be the wrong trade-off in production.
 */
export function ensureSecureDataDir(dir: string): void {
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true, mode: DIR_MODE })
  }
  try {
    chmodSync(dir, DIR_MODE)
  } catch (err) {
    logger.warn({ err, dir }, 'Could not chmod data directory to 0700')
  }

  const htaccessPath = `${dir}/.htaccess`
  // Only write if missing or content drifted, so we don't churn mtimes on
  // every save() call.
  let needsWrite = !existsSync(htaccessPath)
  if (!needsWrite) {
    try {
      const stat = statSync(htaccessPath)
      // Cheap drift detection: byte length must match.
      needsWrite = stat.size !== Buffer.byteLength(HTACCESS_BODY, 'utf-8')
    } catch {
      needsWrite = true
    }
  }
  if (needsWrite) {
    writeFileSync(htaccessPath, HTACCESS_BODY, { mode: FILE_MODE })
  }
}

/**
 * Writes `data` to `path` atomically with mode 0600.
 *
 * Pattern: write `<path>.tmp` → chmod 0600 → rename. The rename inherits
 * the temp file's permissions on POSIX, but we also chmod the canonical
 * path explicitly because Node's writeFileSync mode option is honored only
 * on file creation, not on overwrite of an existing file with looser perms.
 */
export function atomicWriteJson(path: string, data: unknown): void {
  ensureSecureDataDir(dirname(path))
  const tmp = `${path}.tmp`
  writeFileSync(tmp, JSON.stringify(data, null, 2), { mode: FILE_MODE })
  renameSync(tmp, path)
  try {
    chmodSync(path, FILE_MODE)
  } catch (err) {
    logger.warn({ err, path }, 'Could not chmod data file to 0600')
  }
}
