export const SURVEY_POINTS_ABI = [
  'function totalPoints(address wallet) external view returns (uint256)',
  'function surveyPoints(address wallet, uint256 surveyId) external view returns (uint8)',
  'function claimed(address wallet, uint256 surveyId) external view returns (bool)',
  'function getSurveyInfo(uint256 surveyId) external view returns (bytes32 secretHash, uint8 points, uint256 maxClaims, uint256 claimCount, bool active, uint256 registeredAt)',
  'function isAdmin(address account) external view returns (bool)',
  'function addAdmin(address account) external',
  'function removeAdmin(address account) external',
  'function ADMIN_ROLE() external view returns (bytes32)',
  'function hasRole(bytes32 role, address account) external view returns (bool)',
  'event PointsAwarded(address indexed wallet, uint256 indexed surveyId, uint8 points)',
  'event SurveyRegistered(uint256 indexed surveyId, uint8 points, uint256 maxClaims)',
  'event SurveyDeactivated(uint256 indexed surveyId)',
  'event RoleGranted(bytes32 indexed role, address indexed account, address indexed sender)',
  'event RoleRevoked(bytes32 indexed role, address indexed account, address indexed sender)',
] as const
