/**
 * @module template
 *
 * Generates downloadable survey templates for SoSci Survey (.xml) and
 * LimeSurvey (.lss). Each template embeds a styled "claim your points"
 * button.
 *
 * V2 design:
 *   The template no longer hard-codes a plaintext shared secret in the
 *   claim URL. Instead the goodbye page contains a small PHP snippet
 *   that runs on the SoSci server, generates a one-time nonce per
 *   participant, computes the matching HMAC token using the embedded
 *   per-survey key, and renders the final URL. This means:
 *     1. Every participant sees a unique link they cannot share with
 *        anyone else (the nonce is single-use, enforced by the backend
 *        nonce store).
 *     2. The HMAC key never leaves the SoSci PHP runtime — it is
 *        baked into the template and visible only to admins who
 *        downloaded it. End users see only nonce + token.
 *     3. SoSci must have PHP execution enabled on its goodbye pages
 *        (it is enabled by default on stock SoSci installations).
 *
 * Supported formats:
 *   - **SoSci Survey** – project XML (<surveyProject>) with the snippet
 *                        on the goodbye page.
 *   - **LimeSurvey**   – survey structure (.lss) with the snippet in
 *                        the survey end message (surveyls_endtext).
 */
import { config } from '../config.js'

export type TemplateFormat = 'sosci' | 'limesurvey'

/**
 * PHP+HTML snippet that runs on the survey backend (SoSci or
 * LimeSurvey, both expose PHP) and renders a personalised claim
 * button. Embeds:
 *   - the survey id (numeric, hard-coded)
 *   - the per-survey HMAC key (base64url, hard-coded)
 *   - the public frontend origin (where the claim page lives)
 *
 * Security notes:
 *   - The HMAC key is embedded as a string literal. SoSci users with
 *     access to the survey code can read it; that is acceptable,
 *     because they are the operator anyway. Participants only ever
 *     see the rendered HTML output (URL + button) — never the key.
 *   - `random_bytes` is used for the nonce when available (PHP 7+,
 *     all maintained SoSci installs). Falls back to
 *     `openssl_random_pseudo_bytes` for ancient PHP.
 *   - htmlspecialchars escapes the URL parameters in the rendered <a>
 *     tag to neutralise any future change of base64url encoding that
 *     might introduce HTML-special characters.
 */
function buildPhpSnippet(surveyId: number, surveyKey: string, points: number): string {
  const pointLabel = points > 1 ? 'Versuchspersonenpunkte' : 'Versuchspersonenpunkt'
  const origin = config.frontendUrl
  // Use single quotes inside the PHP literal to avoid the need to escape $.
  // The HMAC key is a base64url string (A-Z a-z 0-9 - _) that cannot
  // contain quotes or backslashes, so direct interpolation is safe.
  return `<?php
// VPP claim button — generated by VPP backend. Do not edit by hand.
// Re-download the template from the admin UI to update the embedded
// HMAC key after a key rotation.
$VPP_FRONTEND  = '${origin}';
$VPP_SURVEY_ID = ${surveyId};
$VPP_KEY_B64   = '${surveyKey}';
$VPP_POINTS    = ${points};

// 16 random bytes -> URL-safe base64 (no padding) -> nonce.
if (function_exists('random_bytes')) {
    $nonce_raw = random_bytes(16);
} else {
    $nonce_raw = openssl_random_pseudo_bytes(16);
}
$nonce = rtrim(strtr(base64_encode($nonce_raw), '+/', '-_'), '=');

// HMAC-SHA256 of the canonical message "v1|<surveyId>|<nonce>".
$key_raw = base64_decode(strtr($VPP_KEY_B64, '-_', '+/'));
$mac_raw = hash_hmac('sha256', 'v1|' . $VPP_SURVEY_ID . '|' . $nonce, $key_raw, true);
$token = rtrim(strtr(base64_encode($mac_raw), '+/', '-_'), '=');

$claim_url = $VPP_FRONTEND . '/claim'
    . '?s=' . $VPP_SURVEY_ID
    . '&n=' . $nonce
    . '&t=' . $token;
?>
<div style="max-width:480px;margin:2rem auto;text-align:center;font-family:system-ui,-apple-system,sans-serif;">
  <div style="font-size:2.5rem;margin-bottom:0.5rem;">&#10003;</div>
  <h2 style="margin:0 0 0.5rem;font-size:1.35rem;color:#111;">Vielen Dank f&#252;r deine Teilnahme!</h2>
  <p style="margin:0.75rem 0;color:#555;font-size:0.95rem;">
    Du erh&#228;ltst <strong><?php echo $VPP_POINTS; ?> ${pointLabel}</strong> f&#252;r diese Umfrage.
    Klicke auf den Button, um deine Punkte einzul&#246;sen.
  </p>
  <a href="<?php echo htmlspecialchars($claim_url, ENT_QUOTES, 'UTF-8'); ?>"
     style="display:inline-block;margin:1rem 0;padding:0.7rem 2rem;background:#2563eb;color:#fff;text-decoration:none;border-radius:0.5rem;font-weight:600;font-size:1rem;">
    Punkte jetzt einl&#246;sen &#8594;
  </a>
  <p style="margin-top:1.5rem;color:#888;font-size:0.8rem;">
    Der Link ist nur einmal g&#252;ltig. Bitte gib ihn nicht weiter.
  </p>
</div>
`
}

/**
 * Generates a SoSci Survey project XML that can be imported directly.
 * The goodbye page contains the PHP snippet that renders a one-time
 * claim URL per participant (see buildPhpSnippet).
 *
 * Import: SoSci Admin > Project > Import (project file).
 */
export function generateSoSciTemplate(surveyId: number, surveyKey: string, points: number): string {
  const timestamp = new Date().toISOString().replace('T', ' ').slice(0, 19)
  const goodbyePhp = buildPhpSnippet(surveyId, surveyKey, points)

  return `<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE surveyProject SYSTEM "doctype.survey.dtd">
<surveyProject version="2.4" timestamp="${timestamp}" program="oFb" progversion="3.8.03 1410">
<title>VPP Survey ${surveyId}</title>
<description />
<attributes.specific program="ofb">
<attr id="language">deu</attr>
</attributes.specific>
<questionnaire>
<title>Fragebogen</title>
<attributes.specific program="ofb">
<attr id="id">base</attr>
<attr id="content">
<![CDATA[<?xml version="1.0"?>
<questionnaire>

<!-- Seite 1 -->
<page intID="1">
</page>


</questionnaire>]]>
</attr>
<attr id="goodbye">
<![CDATA[${goodbyePhp}]]>
</attr>
<attr id="selection">1</attr>
</attributes.specific>
</questionnaire>
</surveyProject>
`
}

/**
 * Generates a LimeSurvey Survey Structure (.lss) that can be imported
 * via "Create survey > Import". The PHP snippet is embedded in the
 * survey end message (surveyls_endtext).
 *
 * Note on LimeSurvey PHP:
 *   LimeSurvey requires the PHP question type or "Allow PHP in the
 *   end message" to be enabled in the survey settings. The snippet
 *   itself is identical to the SoSci version because both engines
 *   ultimately render via PHP on the survey server.
 */
export function generateLimeSurveyTemplate(
  surveyId: number,
  surveyKey: string,
  points: number,
): string {
  const claimHtml = buildPhpSnippet(surveyId, surveyKey, points)

  return `<?xml version="1.0" encoding="UTF-8"?>
<document>
 <LimeSurveyDocType>Survey</LimeSurveyDocType>
 <DBVersion>640</DBVersion>
 <languages>
  <language>de</language>
 </languages>
 <groups>
  <fields>
   <fieldname>gid</fieldname>
   <fieldname>sid</fieldname>
   <fieldname>group_order</fieldname>
   <fieldname>randomization_group</fieldname>
   <fieldname>grelevance</fieldname>
  </fields>
  <rows>
   <row>
    <gid><![CDATA[1]]></gid>
    <sid><![CDATA[0]]></sid>
    <group_order><![CDATA[1]]></group_order>
    <randomization_group/>
    <grelevance><![CDATA[1]]></grelevance>
   </row>
  </rows>
 </groups>
 <group_l10ns>
  <fields>
   <fieldname>id</fieldname>
   <fieldname>gid</fieldname>
   <fieldname>group_name</fieldname>
   <fieldname>description</fieldname>
   <fieldname>language</fieldname>
  </fields>
  <rows>
   <row>
    <id><![CDATA[1]]></id>
    <gid><![CDATA[1]]></gid>
    <group_name><![CDATA[Umfrage]]></group_name>
    <description><![CDATA[F\u00fcge hier deine Fragen hinzu.]]></description>
    <language><![CDATA[de]]></language>
   </row>
  </rows>
 </group_l10ns>
 <surveys>
  <fields>
   <fieldname>sid</fieldname>
   <fieldname>gsid</fieldname>
   <fieldname>admin</fieldname>
   <fieldname>active</fieldname>
   <fieldname>anonymized</fieldname>
   <fieldname>format</fieldname>
   <fieldname>language</fieldname>
   <fieldname>datestamp</fieldname>
   <fieldname>usecookie</fieldname>
   <fieldname>showwelcome</fieldname>
   <fieldname>autoredirect</fieldname>
  </fields>
  <rows>
   <row>
    <sid><![CDATA[0]]></sid>
    <gsid><![CDATA[1]]></gsid>
    <admin><![CDATA[Admin]]></admin>
    <active><![CDATA[N]]></active>
    <anonymized><![CDATA[Y]]></anonymized>
    <format><![CDATA[G]]></format>
    <language><![CDATA[de]]></language>
    <datestamp><![CDATA[N]]></datestamp>
    <usecookie><![CDATA[N]]></usecookie>
    <showwelcome><![CDATA[Y]]></showwelcome>
    <autoredirect><![CDATA[N]]></autoredirect>
   </row>
  </rows>
 </surveys>
 <surveys_languagesettings>
  <fields>
   <fieldname>surveyls_survey_id</fieldname>
   <fieldname>surveyls_language</fieldname>
   <fieldname>surveyls_title</fieldname>
   <fieldname>surveyls_description</fieldname>
   <fieldname>surveyls_welcometext</fieldname>
   <fieldname>surveyls_endtext</fieldname>
   <fieldname>surveyls_dateformat</fieldname>
   <fieldname>surveyls_numberformat</fieldname>
  </fields>
  <rows>
   <row>
    <surveyls_survey_id><![CDATA[0]]></surveyls_survey_id>
    <surveyls_language><![CDATA[de]]></surveyls_language>
    <surveyls_title><![CDATA[VPP Umfrage ${surveyId}]]></surveyls_title>
    <surveyls_description/>
    <surveyls_welcometext><![CDATA[Willkommen zur Umfrage. Deine Antworten werden anonym erfasst.]]></surveyls_welcometext>
    <surveyls_endtext><![CDATA[${claimHtml}]]></surveyls_endtext>
    <surveyls_dateformat><![CDATA[1]]></surveyls_dateformat>
    <surveyls_numberformat><![CDATA[0]]></surveyls_numberformat>
   </row>
  </rows>
 </surveys_languagesettings>
</document>
`
}
